API_HOST_URL: 'https://indonesiax.co.id' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'IndonesiaX'
FEEDBACK_EMAIL_ADDRESS: 'hostmaster@indonesiax.co.id'
SOCIAL_FEATURES_ENABLED: false
REGISTRATION_API_DEPRECATED: true
